name: "üìã Release Extension"

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+[0-9A-Za-z]?'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-extension

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: amd64
          - os: ubuntu-24.04-arm
            arch: arm64
        php: [ '8.2', '8.3', '8.4', '8.5' ]
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: ‚¨áÔ∏è Git clone the repository
        uses: actions/checkout@v4

      - name: üîê Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: üì¶ Build
        run: |
          IMAGE=${{ env.REGISTRY }}/${{ github.repository }}-extension:${{ github.ref_name }}
          cd extension
          docker build --no-cache --build-arg=PHP_VERSION=${{ matrix.php }} -t ${IMAGE}-php${{ matrix.php }}-${{ matrix.arch }} .

      - name: ‚òÅÔ∏è Push
        run: |
          IMAGE=${{ env.REGISTRY }}/${{ github.repository }}-extension:${{ github.ref_name }}
          docker push ${IMAGE}-php${{ matrix.php }}-${{matrix.arch}}

  manifest:
    name: Manifest
    runs-on: ubuntu-latest
    needs: build

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    strategy:
      matrix:
        php: [ '8.2', '8.3', '8.4', '8.5' ]

    steps:
      - name: üîê Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: ‚òÅÔ∏è Push
        run: |
          IMAGE=${{ env.REGISTRY }}/${{ github.repository }}-extension:${{ github.ref_name }}
          docker manifest create ${IMAGE}-php${{ matrix.php }} --amend ${IMAGE}-php${{ matrix.php }}-arm64 --amend ${IMAGE}-php${{ matrix.php }}-amd64
          docker manifest push ${IMAGE}-php${{ matrix.php }}
